# Generated by Django 4.2.6 on 2023-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('idioma', models.CharField(max_length=20)),
                ('imagem', models.ImageField(upload_to='livros/')),
            ],
        ),
    ]
