# Generated by Django 4.2.7 on 2023-11-09 17:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amanda', '0003_delete_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['autor'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=5.0)])),
                ('comentario', models.TextField()),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['nota'],
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('editora', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'ordering': ['editora'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['genero'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='livros/')),
                ('sinopse', models.TextField()),
                ('status', models.CharField(default='Disponível', max_length=30)),
                ('pdf_disponivel', models.FileField(upload_to='pdfs/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.editora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.genero')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.livro'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
