# Generated by Django 4.2.7 on 2023-11-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0003_delete_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_Autor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_da_Editora', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_Genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=255)),
                ('Ano_de_Publicacao', models.CharField(max_length=4)),
                ('Idioma', models.CharField(max_length=50)),
                ('Imagem', models.CharField(max_length=255)),
                ('Sinopse', models.TextField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.autor')),
                ('Editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.editora')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.genero')),
            ],
        ),
    ]
