# Generated by Django 4.2.7 on 2023-11-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0003_delete_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=100)),
                ('ano_publicacao', models.CharField(max_length=4)),
                ('idioma', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
