# Generated by Django 4.2.7 on 2023-11-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0003_delete_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='livros/')),
                ('sinopse', models.TextField()),
                ('status', models.CharField(default='Disponível', max_length=20)),
                ('pdf_disponivel', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.livro'),
        ),
    ]
