# Generated by Django 4.2.7 on 2023-11-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0004_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.livro')),
            ],
        ),
    ]
