# Generated by Django 4.2.7 on 2023-11-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0005_rename_livros_livro_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='livro',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
