# Generated by Django 4.2.7 on 2023-11-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0004_avaliacao_livro_delete_comment_avaliacao_livro'),
        ('amanda', '0006_remove_status_livro_delete_livro_delete_status'),
    ]

    operations = [
    ]
