# Generated by Django 4.2.7 on 2023-11-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0006_autor_editora_genero_alter_livro_autor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editora',
            options={'ordering': ['editora'], 'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['genero'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
    ]
