# Generated by Django 4.2.7 on 2023-11-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0008_alter_avaliacao_options_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={},
        ),
    ]
