# Generated by Django 4.2.7 on 2023-11-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amanda', '0009_merge_20231109_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='livros/')),
                ('sinopse', models.TextField()),
                ('status', models.CharField(default='Disponível', max_length=30)),
                ('pdf_disponivel', models.FileField(upload_to='pdfs/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.editora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amanda.genero')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
